# ref: https://docs.minecraftforge.net/en/latest/gettingstarted/modfiles/#modstoml

modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "${modLicense}"
issueTrackerURL = "https://github.com/gnya/${modId}/issues"
clientSideOnly = false

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
displayURL = "https://github.com/gnya/${modId}/"
authors = "${modAuthors}"
displayTest = "MATCH_VERSION"
description = "${modDescription}"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "${forgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"
