name: Java CI with Gradle

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # gradle.propertiesからjavaVersionを抽出して利用する
      - name: Export java version
        run: |
          JAVA_VER=$(grep 'javaVersion' gradle.properties | cut -d'=' -f2)
          echo "JAVA_VERSION=$JAVA_VER" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build